version: '3'
services:
    django:
        restart: always
        build: ./django
        expose:
            - "3031"
        depends_on:
            - mariadb
        command: bash -c "python manage.py migrate && gunicorn my_docker_django_project.wsgi -b 0.0.0.0:3031"
        volumes:
            - "staticdata:/opt/static/"
        entrypoint: ./wait-for-mariadb.sh mariadb:3306
    
    nginx:
        image: nginx
        restart: always
        depends_on: 
            - django
        ports:
            - "80:80"
        volumes:
            - "./nginx/:/etc/nginx"
            - "staticdata:/opt/code/static"

    mariadb:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        volumes:
            - "dbdata:/var/lib/mariadb/data"
        env_file:
            - ./mariadb.env

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    dbdata:
    staticdata: